name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Create release tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d-%H%M%S')"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Archive build
        run: |
          cd dist
          zip -r ../build.zip .
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          name: Release ${{ steps.create_tag.outputs.tag_name }}
          body: |
            Automated release from GitHub Actions
            Commit: ${{ github.sha }}
          files: build.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
